### ISSUE TITLE
uTest 0.4.0

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/utest#85]
It's been exactly 1 year and 1 day since the last release `0.3.1` was published. In the interim, there have been a lot of improvements suggested. This document aggregates them into one place and sets the plan for what would go into a theoretical "uTest 0.4.0" if/when it ends up getting released.

uTest 0.4.0 Goals
=================

- [ ] Macro asserts
    - [x] Allow "capture" and automatic-printing of arbitrary expressions
    - [ ] Allow "tagging" of expressions with a string that gets added to the 
      error message, the way it works in normal `Predef.assert(pred: Boolean, tag: Any)`
    - [x] Variadic `assert()` method should aggregate multiple errors, wrap them 
      and throw all together, rather than just throwing the first one
    - [x] Built-in `==>` asserts for pretty tests that can be lifted into docs #75
    - [x] `compileError` check should check for `compileTimeOnly` subtrees, which currently fail to make it pass
- [ ] Selective test running
    - [x] Running any individual test block should be as easy as running any 
      entire file
    - [ ] Should be able to run multiple tests easily.
    
- [ ] Test features
    - [ ] Tagging tests
        - Via `@annotations`? `tag(foo){...}`? Not sure
        - And running them by tag 
        - Maybe having some default tags? #17
    - [x] Retries
        - [x] Test level *and* expression-level
    - [x] Implicit test-path made available so tests can use their name to e.g. 
      load files or set working directories #71 #72
    - [x] Want some kind of setup/teardown, 
        - [x] both per-test 
        - [x] per-suite
        - [x] and per-run    

- [ ] Configurability
    - [x] Features
        - [ ] Pretty-printing (e.g. to swap in com.lihaoyi/pprint)
        - [x] Truncation length (maybe part of pretty-printing?)
        - [x] Reporter (e.g. to reduce verbosity) #77 #41 #39
        - [x] Color/no-color #51
    - [ ] Technique
        - [x] In-code config `object`; instantiate and override whatever
        - [x] Not sure if this is even possible with Scala.js?
        - [ ] Maybe compatible with SBT configurations??? #42

- [ ] Compatability
    - [ ] Make sure works with `fork in Test := true` #53 #25
    - [ ] Make sure JUnit XML reports are sane #69

- [x] Docs
    - [x] First impression should be "getting started with SBT"
    - [x] Everything else can come later

**Comment by lihaoyi** [comment]
This work is happening in the `test` branch

**Comment by japgolly** [comment]
A feature I'd love to see on the list is the ability to time tests and print the slowest 10 tests and/or all tests that took longer than x.

**Comment by wenLiangcan** [comment]
@japgolly +1

**Comment by lihaoyi** [comment]
I released 0.4.3 and it seems to work in the projects I'm using it in

https://github.com/lihaoyi/utest#µtest-043

Give it a shot and let me know what you guys think. It shouldn't be a huge change to be honest, but overall more configurable and with some niceties. 

I'm closing this for now, though further progress may happen when it happens
